=== Serg-Maximchuk/imcms/src/main/resources-conf/schema-upgrade.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="schema-upgrade">
      <xs:complexType>
        <xs:sequence>
          <xs:element ref="diff" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
      </xs:complexType>
    </xs:element>


    <xs:element name="diff">
      <xs:complexType>
        <xs:sequence>
          <xs:element ref="vendor" minOccurs="1" maxOccurs="2"/>
        </xs:sequence>

        <xs:attribute name="from" type="xs:double" use="required"/>
        <xs:attribute name="to" type="xs:double" use="required"/>
      </xs:complexType>
    </xs:element>


    <xs:element name="vendor">
      <xs:complexType>
        <xs:sequence>
          <xs:element ref="script" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" use="required" type="vendor-name"/>
      </xs:complexType>
    </xs:element>


    <xs:element name="script">
      <xs:complexType>
        <xs:attribute name="location" type="xs:string" use="required"/>
      </xs:complexType>
    </xs:element>


    <xs:simpleType name="vendor-name">
      <xs:restriction base="xs:string">
        <xs:enumeration value="mysql"/>
        <xs:enumeration value="mssql"/>
      </xs:restriction>
    </xs:simpleType>
    
</xs:schema>

=== Serg-Maximchuk/imcms/src/test/resources/schema-upgrade-with-non-existing-scripts.xml
<schema-upgrade
    xsi:noNamespaceSchemaLocation="../../main/resources-conf/schema-upgrade.xsd" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    
  <diff version="6.11">
    <vendor name="mysql">
      <script location="A.sql"/>
      <script location="B.sql"/>
    </vendor>

    <vendor name="mssql">
      <script location="A$.sql"/>
      <script location="B$.sql"/>
    </vendor>
  </diff>

  <diff version="6.12">
    <vendor name="mysql">
      <script location="C.sql"/>
      <script location="D.sql"/>
    </vendor>

    <vendor name="mssql">
      <script location="C$.sql"/>
      <script location="D$.sql"/>
    </vendor>
  </diff>

  <diff version="6.13">
    <vendor name="mysql">
      <script location="E.sql"/>
      <script location="F.sql"/>
    </vendor>

    <vendor name="mssql">
      <script location="E$.sql"/>
      <script location="F$.sql"/>
    </vendor>
  </diff>
</schema-upgrade>
